### ISSUE TITLE
SentencePieceProcessor' object has no attribute 'vocab_size

### ISSUE THREAD

**Issue by wangzhang2991** [speechbrain/speechbrain#816]
This error occurred while running the script， the path is "speechbrain/recipes/AISHELL-1/Tokenizer/train.py"

I checked "SentencePiece.py", 
        import sentencepiece as spm
        self.sp = spm.SentencePieceProcessor()
        self.sp.load(self.prefix_model_file + ".model")
  then "sp.vocab_size()" is right ?
  
File "train.py", line 52, in <module>
    hparams["tokenizer"]()
  File "/opt/miniconda3/lib/python3.6/site-packages/speechbrain-0.5.7-py3.6.egg/speechbrain/tokenizers/SentencePiece.py", line 191, in __init__
    self._check_coverage_from_bpe(annotation_list_to_check)
  File "/opt/miniconda3/lib/python3.6/site-packages/speechbrain-0.5.7-py3.6.egg/speechbrain/tokenizers/SentencePiece.py", line 374, in _check_coverage_from_bpe
    "Tokenizer vocab size: " + str(self.sp.vocab_size())
  File "/opt/miniconda3/lib/python3.6/site-packages/sentencepiece.py", line 105, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SentencePieceProcessor, name)
  File "/opt/miniconda3/lib/python3.6/site-packages/sentencepiece.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'SentencePieceProcessor' object has no attribute 'vocab_size

**Comment by mravanelli** [comment]
Weird, I just tried in and I was able to run the script without issues. Could you install the latest version of sentencepiece? I also work with python 3.8 or 3.9 (3.6 is too old and not supported by SpeechBrain).

**Comment by wangzhang2991** [comment]
thanks!!
