### PR TITLE
Pin `click` version

### PR DESCRIPTION
**Pull request by calvinballing**
An update to `click` causes `black` to fail with
`ImportError: cannot import name '_unicodefun' from 'click' (/Users/jimhays/.cache/pre-commit/repoef_0ghls/py_env-python3/lib/python3.10/site-packages/click/__init__.py)`

This pins `click` at a working version.

For more information, see:
https://github.com/dask/distributed/issues/6013

### CODE REVIEW

**Comment by anautsch** [comment]
The error is reproducible, timely PR!

When testing it, after updating the installed click version, the error was still persistent, though - on the terminal, I ran the depending git hook: `pre-commit run --all-files`

The black repo also worked on this here:
https://github.com/psf/black/issues/2964

Please update the `.pre-commit-config.yaml` file as well - a working snippet might be:
```
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        types: [python]
        additional_dependencies: ['click==8.0.4']
```

It also works with `['click >= 6.6, <= 8.0.4']` :)

Once this change is in the PR, we can close it.
(At some later point, we should migrate to the latest black version.)

**Comment by anautsch** [comment]
The error is reproducible, timely PR!

When testing it, after updating the installed click version, the error was still persistent, though - on the terminal, I ran the depending git hook: `pre-commit run --all-files`

The black repo also worked on this here:
https://github.com/psf/black/issues/2964

Please update the `.pre-commit-config.yaml` file as well - a working snippet might be:
```
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        types: [python]
        additional_dependencies: ['click==8.0.4']
```

It also works with `['click >= 6.6, <= 8.0.4']` :)

Once this change is in the PR, we can close it.
(At some later point, we should migrate to the latest black version.)

**Comment by anautsch** [comment]
closed for #1367
