### ISSUE TITLE
AttributeError: 'function' object has no attribute 'keys'

### ISSUE THREAD

**Issue by KacperKubara** [speechbrain/speechbrain#1224]
While running pretrained models tutorial (https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing) on Google colab I've encountered the following error:
``` bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-4ab510a1a511> in <module>()
----> 1 asr_model.modules.keys()

AttributeError: 'function' object has no attribute 'keys'
```

This occurs after following lines:
``` Python
from speechbrain.pretrained import EncoderDecoderASR
asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="./pretrained_ASR")
asr_model.modules.keys()
```

Any ideas why it happens?

**Comment by mravanelli** [comment]
Hi @KacperKubara ,thank you for point out this issue. I'm indeed able to replicate it (just bu running the tutorial that you linked). My feeling is that this is connected to a change we recently did to the interfaces. It is quite weird because asr_model.modules should be a dictionary but it looks like it is a method now.  @Gastron and @aheba might be able to figure out what is going on here...

**Comment by KacperKubara** [comment]
Ok great, do you remember in which version this has roughly been introduced? I want to revert to the older repository version for now to run the notebook.

**Comment by mravanelli** [comment]
If my speculation is correct, it should work with SpeechBrain 0.5.10. In
anycase, we have to fix the issue even with the latest version of
SpeechBrain.

**Comment by Gastron** [comment]
Ah, the notebook should be changed. We made the `Pretrained` interfaces into `torch.nn.Modules`, which have a `.modules()` method. We changed the old `Pretrained.modules` attribute to `Pretrained.mods`.

**Comment by KacperKubara** [comment]
Ok thanks, it works when I change it to `mods`. Besides, docs need an update as there still is old parameter `modules`: https://speechbrain.readthedocs.io/en/latest/API/speechbrain.pretrained.interfaces.html

**Comment by Gastron** [comment]
The argument was actually kept as modules, just the internal attribute name was changed. Could add a note in the docstring though-

**Comment by mravanelli** [comment]
I changed the tutorial. We now have to figure out what is happening with the documentation. 
I'm wondering though if there are others tutorials affected by it. This leads us to a bigger topic: "how can we make sure the tutorials are compliant with the latest code?". I'm not sure if that is possible, but maybe there is a way to create some sort of test that automatically downloads the tutorials and runs the code within them. Any idea on that side?

**Comment by Gastron** [comment]
Turns out I added a note in the docstring already, but the docs generation was failing so that note was not visible. PR #1228 hopefully fixes docs generation so the modules->mods note (among other changes) become visible.
